### ISSUE TITLE
Bunny engine persistence

### ISSUE THREAD

**Issue by StarvingMarvin** [rabix/bunny#88]
Bunny engine should be able to persist it's state in a way that it can be reliably restarted during task execution.

- [x] Optimize current memory bottlenecks and estimate maximal number of running tasks one engine instance can handle #119 
- [x] Move JobService from rest module to engine #186 
- [ ] ~~Refactor models and data service interfaces to separate module (store) #120~~
- [x] Implement Postgre based implementation of store interfaces #118 
- [x] Deduplicate in-memory data (apps and DAGs) #121 
- [x] Create proper benchmarks for 1K, 2K and 5K WGS workflows with/without persistence #122
- [x] Create tests for all known workflows the with persistence feature enabled #123  
- [x] Enable Bunny to recover from forced shutdown #124 
- [x] Create in-memory repository store for local executions #125 
- [x] Use batch inserts and updates to flush event processor caches #135
- [x] Remove unnecessary data from DB after Job completed event #141
- [x] Liquibase migrations #158
